"""Learn and persist the visual vocabulary (the k 128-D visual words)."""

from __future__ import annotations

import pickle
from pathlib import Path

import numpy as np
from sklearn.cluster import MiniBatchKMeans


def learn_vocabulary(descriptors: np.ndarray, clusters: int, seed: int) -> np.ndarray:
    """Cluster sampled SIFT rows with k-means and return their centroid matrix."""
    if clusters < 2:
        raise ValueError("--clusters must be at least 2")
    if len(descriptors) < clusters:
        raise ValueError(f"Need at least {clusters} descriptors; collected only {len(descriptors)}")

    # MiniBatchKMeans is the same k-means objective with memory-friendly updates.
    kmeans = MiniBatchKMeans(
        n_clusters=clusters,
        batch_size=min(4_096, len(descriptors)),
        n_init=10,
        random_state=seed,
        verbose=0,
    )
    kmeans.fit(descriptors)
    return kmeans.cluster_centers_.astype(np.float32)


def save_vocabulary(vocabulary: np.ndarray, destination: Path) -> None:
    """Save visual-word centroids to models/vocabulary.pkl for future runs."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    with destination.open("wb") as file:
        # The dictionary leaves room for metadata without changing the file format.
        pickle.dump({"centroids": vocabulary}, file)


def load_vocabulary(source: Path, expected_clusters: int) -> np.ndarray:
    """Load and validate a vocabulary previously generated by save_vocabulary."""
    if not source.is_file():
        raise FileNotFoundError(f"Cannot reuse missing vocabulary: {source}")
    with source.open("rb") as file:
        vocabulary = pickle.load(file)["centroids"]
    vocabulary = np.asarray(vocabulary, dtype=np.float32)
    if vocabulary.shape != (expected_clusters, 128):
        raise ValueError(
            f"Expected a ({expected_clusters}, 128) vocabulary, found {vocabulary.shape}"
        )
    return vocabulary
